07 lifecycle
NinZZya/hw-otus pull request #2
Opened 2020-10-31 21:41 UTC by NinZZya

2020-11-01 12:08 UTC, AntiHero commented on package.json
> +    "test": "npm run test:jest && npm run test:loki && npm run lint",
npm run и npx писать в скриптах не нужно, просто пишешь `test: jest && test:loki ...`

2020-11-01 12:11 UTC, AntiHero commented
впринципе советую тебе придерживаться какого-то одного шаблона наименования ветвей, 07-lifecycle, но 4я домашка у тебя не 04-05-homework, а homework-4-5 + у тебя в ветке с этой домашкой оказалась домашка 4-5

2020-11-01 12:15 UTC, AntiHero commented on package.json
> +    "test": "npm run test:jest && npm run test:loki && npm run lint",
и поправь пожалуйста скрипт start, правильно `--mode**=**development`, а не --mode отдельно, development отдельно

2020-11-01 12:40 UTC, AntiHero commented on src/componets/Card/Card.tsx
> +import styled from "@emotion/styled";
решил использовать emotion, а зачем тогда к webpack сss прикручивал?) ты бы одно что-нибудь выбрал или import css или emotion)

2020-11-01 12:43 UTC, AntiHero commented on src/componets/Indicator/Indicator.stories.tsx
> +import { Card } from "../Card/Card";
посмотри как прикрутить к webpack resolve/alias, чтобы избавиться от путей вида `../../../имя_твоего_модуля` пригодится

2020-11-01 13:04 UTC, NinZZya commented on src/componets/Indicator/Indicator.stories.tsx
> +import { Card } from "../Card/Card";
Я делал. Но ругается TS. Находил решения на stackoverflow и GitHub. Не помогло 😩

2020-11-01 16:22 UTC, AntiHero commented on src/componets/index.ts
> +export * from "./Card/Card";
Зачем???

2020-11-01 16:23 UTC, AntiHero commented on src/matchers/toBeWithinRange.ts
> +export {};
?

2020-11-01 17:25 UTC, AntiHero commented
+ прикрути какой-нибудь метод к классовой компоненте, чтобы привязать к нему контекст в соответсвии с заданием

2020-11-01 17:25 UTC, AntiHero requested changes

2020-11-01 17:59 UTC, AntiHero commented on src/componets/Indicator/Indicator.stories.tsx
> +import { Card } from "../Card/Card";
> Я делал. Но ругается TS. Находил решения на stackoverflow и GitHub. Не помогло 😩

webpack.config.js 
...
`resolve: {
    extensions: [".js", ".jsx", ".ts", ".tsx", ".json"],
    alias: {
      '@': path.resolve(__dirname, 'src'),
    }
  },
...
`
tsconfig.js 

`{
  "compilerOptions": {
    ...
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
  }`

2020-11-01 18:02 UTC, NinZZya commented on src/componets/Indicator/Indicator.stories.tsx
> +import { Card } from "../Card/Card";
Да. Так и делал. Webpack собирает, а TS ругается

2020-11-19 11:50 UTC, AntiHero commented
+ ещё можно убирать компонент, в котором ты делаешь автогенерацию курса после того как ErrorBoundary отловил ошибку, иначе получается можно генерировать рандомный курс, но приложение состояния не меняет

2020-11-22 10:28 UTC, AntiHero commented on src/modules/InfoUSD/components/RandomCourse/RandomCourse.e2e.test.tsx
> +});
а причём тут e2e?) это не e2e тест

2020-12-25 16:41 UTC, closed without merging